### ISSUE TITLE
Upgrading RainLab's Blog to Winter causes SQL errors

### ISSUE THREAD

**Issue by 01Kuzma** [wintercms/wn-blog-plugin#33] opened 2023-02-05 18:59 UTC
Hi!
I'm finishing the [upgrade process](https://github.com/wintercms/winter/discussions/832#discussioncomment-4869681) from October to Winter CMS

Having issues with this plugin.
The Rainlab Blog version was `1.6.3`
I've removed the blog's folder from `rainlab` dir and though backend installed the Winter.Blog.

After the install error:
![image](https://user-images.githubusercontent.com/569504/217016774-002bbf76-118c-4b09-b045-d9e2bb9132e3.png)

Accessing the `Blog` from this URL- `/backend/winter/blog/posts`, I'm getting these errors:

![image](https://user-images.githubusercontent.com/569504/216839184-dc7f150c-21e0-4f6b-bd03-bc3d6ac28748.png)

And the Plugin shows mixed data: the version is 1.6.3, but author - Winter CMS
![image](https://user-images.githubusercontent.com/569504/216990426-ad7040d7-13ef-4ca0-8bfb-7d3f314a9830.png)

P.S. it seems that it's affecting all plugins, I've done the same procedures with Sitemap plugin. It also throws an error.

**Comment by 01Kuzma** [comment] 2023-02-22 17:11
@LukeTowers , @bennothommo any possible workarounds?

**Comment by LukeTowers** [comment] 2023-02-22 21:11
@01Kuzma the problem is that this plugin currently claims to replace v1.5 and below of the RainLab.Blog plugin but you had 1.6.3 installed (https://github.com/wintercms/wn-blog-plugin/blob/main/Plugin.php#L21). After reviewing https://github.com/rainlab/blog-plugin/blob/master/updates/version.yaml I see that there's no reason why we can't bump it to 1.7.0 now.

**Comment by LukeTowers** [comment] 2023-02-22 21:12
Try https://github.com/wintercms/wn-blog-plugin/commit/5e10e7a11aa89fd1f75546ba9bb6450cd4cd8ca2

**Comment by 01Kuzma** [comment] 2023-03-01 12:23
@LukeTowers, I've changed it in my `Plugin.php`, but the error remains:
![image](https://user-images.githubusercontent.com/569504/222138370-2fbd7d2c-d84d-478e-b7bf-be6b6ed58b00.png)

**Comment by LukeTowers** [comment] 2023-03-01 15:38
@01Kuzma what is in your plugin versions and plugin history tables? You should get those tables back to what they were before you first tried to install winter.blog, double check that the current version of rainlab blog is less than or equal to 1.7.0 and then replace the rainlab plugin with the winter plugin and run `artisan migrate`.

**Comment by 01Kuzma** [comment] 2023-03-01 16:49
@LukeTowers , the october's blog version was `1.6.3`, the plugin history tables shows the same:
![image](https://user-images.githubusercontent.com/569504/222205718-4b7c3b95-f3fe-49b2-865b-7573584f3a1f.png)

Before the upgrade I've removed october blog's folder from `plugins\rainlab\blog`

The folder with files `plugins\winter\blog\` already exists. Once I run `artisan migrate` I get:
![image](https://user-images.githubusercontent.com/569504/222206820-edc32ec1-517a-413d-b088-c5498a2f4724.png)

**Comment by LukeTowers** [comment] 2023-03-01 19:01
What does the plugin_versions table look like?

**Comment by 01Kuzma** [comment] 2023-03-01 19:12
@LukeTowers , here it is:
![image](https://user-images.githubusercontent.com/569504/222240874-798c2207-b790-4f82-8db6-600cf1d6ef70.png)

**Comment by LukeTowers** [comment] 2023-03-02 00:58
@01Kuzma if you run `php artisan winter:version`, what's the result?

**Comment by 01Kuzma** [comment] 2023-03-02 07:54
@LukeTowers it's 1.2.1
![image](https://user-images.githubusercontent.com/569504/222365945-8e71cba8-a464-45ef-95d0-943474f85d31.png)

**Comment by 01Kuzma** [comment] 2023-03-03 12:22
@LukeTowers any thoughts?

**Comment by LukeTowers** [comment] 2023-03-03 19:04
@01Kuzma I was able to reproduce the issue and I've pushed a fix for it: https://github.com/wintercms/winter/commit/482d7b5e1d6fd4ecdd43e6e6709c5882af17ee16 You should be able to either run `composer update` to get that commit if you're running `dev-develop` or just apply it manually locally and it should work.

**Closed** 2023-03-03 19:03 UTC
Labels: Type: Bug

**Comment by LukeTowers** [comment] 2023-03-03 19:12
@01Kuzma you'll also need https://github.com/wintercms/winter/commit/a2988a802552aed58c6213b2ac14e1f788be9a31 🤦

**Comment by 01Kuzma** [comment] 2023-03-03 20:08
@LukeTowers , I've run `composer update` and it seems that the mentioned files are changed, but the error is the same...
Then I run `php artisan migrate`, no luck.
Or I'm missing some commands? I'm total newbie in composer

**Comment by LukeTowers** [comment] 2023-03-03 20:26
Does your winter.blog Plugin.php file still include the 1.7.0 reference?

**Comment by 01Kuzma** [comment] 2023-03-03 20:29
You mean in `composer.json`?
Here is a part of it:

```
    "require": {
        "php": "^8.0.2",
        "winter/storm": "dev-develop as 1.2",
        "winter/wn-system-module": "dev-develop",
        "winter/wn-backend-module": "dev-develop",
        "winter/wn-cms-module": "dev-develop",
        "laravel/framework": "^9.1",
        "wikimedia/composer-merge-plugin": "~2.0.1",
        "offline/oc-responsiveimages-plugin": "dev-develop",
        "winter/wn-blog-plugin": "^2.1"
    },
```

**Comment by 01Kuzma** [comment] 2023-03-03 20:33
@LukeTowers , pardon me. I've changed the `'replaces'    => ['RainLab.Blog' => '<= 1.5.0'],`  to `'replaces'    => ['RainLab.Blog' => '<= 1.7.0'],`.
Run `winter:up and composer update`. Now those upgrade errors gone, but there are some mess with data. Frontend doesn't display the layout and accessing any post throws this error;
![image](https://user-images.githubusercontent.com/569504/222823510-56b767ff-4c78-40c4-a9cc-5724400d8010.png)

**Comment by LukeTowers** [comment] 2023-03-05 04:37
Looks like the ClarkNguyen.BlogBreadCrumbs plugin that you have isn't playing nice with the plugin replacement system, it looks like it's using manual joins and hard coded table names rather than referencing the model classes. I'd have to see it's code to know for sure, but I'd recommend not using it.

**Comment by 01Kuzma** [comment] 2023-03-05 14:25
Thank you, I've removed it, now it seems to load with one issue left at this current moment.
Is there an alternative from Winter for Blog Bread Crumbs?
What is strange, is that after the plugin's upgrade, no styles are applied to the layout. Also no errors in console. Could it be related to Blog's upgrade?

Just a sample how it's shown now:
![image](https://user-images.githubusercontent.com/569504/222966371-20d51208-39ae-4481-92c1-8ef5bf33006f.png)


P.S. I will further upgrade left rainlab's plugins to winter

**Comment by LukeTowers** [comment] 2023-03-05 16:15
I'm not sure, what exactly did that plugin do?

As far as the styles goes, not sure about that. Are there any errors in the combiner output URLs?

**Comment by 01Kuzma** [comment] 2023-03-05 16:52
The plugin displayed blog breadcrumbs, which could be displayed anywhere in the layout.

Regarding styles, that's very weird. Before the plugin update, they were displayed fine, also I tried to disable most of the plugins...
I have this part of the style in the `default.html`:

```
	<style>{{ [ 'assets/css/bootstrap.min.css' ]|inline }}</style>	<-- inline plugin is used, but could be disabled
	
	<link rel="stylesheet" href="{{ [		
		'assets/css/magnific-popup.css',
		'assets/css/owl.carousel.min.css',
		'assets/css/slicknav.min.css',		
		'assets/css/style.css'  <-- this part is ignored after the upgrade
		]|theme }}">
		
	{% styles %}
```

If I change to:

```
	<link rel="stylesheet" href="{{ [		
		'assets/css/style.css',
		'assets/css/magnific-popup.css',
		'assets/css/owl.carousel.min.css',
		'assets/css/slicknav.min.css',		
		]|theme }}">
```

Most part of the `style.css` is loaded, but with many errors + font loading errors


Also, I'm not sure is it related to this blog upgrade issue, I could run app only with PHP 8.1, switching to 8.0 produces this error, while it shouldn't:
`Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.9. in C:\laragon\www\winter3\vendor\composer\platform_check.php on line 24`
But it could be related to some other upgrade problem, so probably I should post it in the discussions

**Comment by LukeTowers** [comment] 2023-03-06 04:03
The composer issue is because you ran composer update under PHP 8.1 but are trying to run the code under PHP 8.0. Run composer update again under PHP 8.0 instead if you want to run the web under 8.0, but I'd recommend leaving both on 8.1

**Comment by 01Kuzma** [comment] 2023-03-06 09:03
Thank you for tip!
Do you have thoughts regarding style issue? Is it related to blog's upgrade or it could be related to winter's dev core update?

**Comment by 01Kuzma** [comment] 2023-03-06 17:16
I've used it from an old example (from October theme). Do you mean that it is wrong?
![image](https://user-images.githubusercontent.com/569504/223182871-96af956e-6451-48f5-9c82-49540b7d3ab3.png)

**Comment by 01Kuzma** [comment] 2023-03-08 16:42
Any thoughts regarding it? 😵
Thank you!

**Comment by LukeTowers** [comment] 2023-03-08 21:45
Eh, that's not really how I would do that at all. Are you building a theme from scratch or are you adapting an existing theme?

**Comment by LukeTowers** [comment] 2023-03-09 20:09
Don't combine those stylesheets, just make each one a separate <link> and don't use the `|inline` filter either.

**Comment by 01Kuzma** [comment] 2023-03-10 18:26
Thank you! 
Everything is working now!
Tell me please, combining assets, as I demonstrated earlier is an obsolete method or I was improperly using it from the beginning?
P.S. I will continue to replace october's plugins with winter

**Comment by LukeTowers** [comment] 2023-03-10 18:37
@01Kuzma it's still a supported method, but you generally wouldn't combine already minified assets, the asset combiner is mostly actually meant for asset compilation (i.e. for LESS / SCSS / SASS styles). Also for asset compilation / processing we now support Laravel Mix (https://wintercms.com/docs/console/asset-compilation) which is a lot more powerful so you may want to take a look at that.

**Comment by 01Kuzma** [comment] 2023-03-10 18:44
Thank you!
