### ISSUE TITLE
Category List component breaks page

### ISSUE THREAD

**Issue by TheWebsiteGuy** [wintercms/wn-blog-plugin#64] opened 2024-05-28 19:19 UTC
Winter Blog 2.1.2 gives this error:

"An exception has been thrown during the rendering of a template ("Cannot assign null to property Winter\Blog\Components\Categories::$currentCategorySlug of type string")"

This happens with a fresh install of Winter and Blog component. 
Can be replicated with the wn-workshop-theme.

The page will load by removing the blog component 'Category List', but not the solution I'm looking for. Any help would be much appreciated.

![Exception](https://github.com/wintercms/wn-blog-plugin/assets/52199309/c5655aaa-333c-423f-8df0-5c0b20353a6d)

**Comment by bennothommo** [comment] 2024-05-29 00:58
@TheWebsiteGuy thanks for the report. I believe this has already been fixed, it just hasn't been released. I'll push a new release out now.

**Comment by bennothommo** [comment] 2024-05-29 01:08
I've pushed out release v2.1.3 for the blog plugin, which should fix this for you.

Duplicate of #38.

**Closed by bennothommo** 2024-05-29 01:08 UTC
Labels: duplicate
