### ISSUE TITLE
After Update - An exception has been thrown during the rendering of a template 

### ISSUE THREAD

**Issue by 01Kuzma** [wintercms/wn-blog-plugin#38] opened 2023-04-29 17:19 UTC
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Just updated the working Winter CMS 1.2.1 with `composer update and winter:up` commands, and it's broken now.
The last update I did was about two months ago.

### Steps to replicate

So, I get the `An exception has been thrown during the rendering of a template ("Undefined array key "about"") in "C:\laragon\www\winter3\themes\mytheme\partials\intro.htm" at line 3.`

`intro.htm` points to `hero1.htm` which `post list component`:

```
[viewBag]

[blogPosts]
pageNumber = "{{ :page }}"
postsPerPage = 7
noPostsMessage = "No posts found"
sortOrder = "random"
categoryPage = "about"
postPage = "blog-post"
==
```

As I understand the error is pointing to `categoryPage = "about"` part.
Before the update, it was working

**Comment by LukeTowers** [comment] 2023-05-03 13:25
@mjauvin I think this issue is caused by the recent refactoring / improvements, are you able to replicate this at all?

**Comment by mjauvin** [comment] 2023-05-04 02:02
Sorry, can't reproduce this.

**Comment by LukeTowers** [comment] 2023-05-05 05:02
@01Kuzma are you able to upload a basic version of your theme that contains just enough to replicate this issue in a fresh install of the winter develop branch and the latest blog plugin?

**Comment by LukeTowers** [comment] 2023-05-05 05:02
@petehalverson side note, would really love to have Octodock back in some capacity 😉

**Comment by 01Kuzma** [comment] 2023-05-06 16:59
Maybe this one will help...
[filmustudija.zip](https://github.com/wintercms/wn-blog-plugin/files/11412920/filmustudija.zip)

**Comment by mjauvin** [comment] 2023-05-06 17:50
I tried your theme, but it is in an unuseable state, plugins/partials missing, layout half beaten to death...

I managed to remove cruft to make it work, and didn't get the error you reported.

Please submit a theme in a usable state and a procedure to replicate your issue with it.

**Comment by 01Kuzma** [comment] 2023-05-06 18:39
@mjauvin , that's strange. I'm getting some other errors with it, the frontend even is not loading throwing errors...
OK, I will try to remake it.

**Comment by 01Kuzma** [comment] 2023-05-07 13:36
@mjauvin I've reviewed it, I don't know what to upload, because the theme is image dependent (pulls them from storage), without them, it looks empty (as you probably saw it).
I've just removed the partials with private information and excessive templates.

Removing the component form the page , of course, removes this error.
But I have another one, accessing page `Portfolio` with two components: `Post list & Category List` gives this:
![image](https://user-images.githubusercontent.com/569504/236680669-c3240870-b89f-474a-a59d-c031be1a31ba.png)

Removing the `Category List` removes the error.

**Comment by mjauvin** [comment] 2023-05-07 15:02
Can you show your Portfolio page ? Specifically, the url and the blogCategories component settings ?

I use this component without any problems on my latest website.

**Comment by mjauvin** [comment] 2023-05-07 15:13
@LukeTowers I was able to generate an error with the blogCategories component when setting an invalid slug to the component slug property. What generates the error is this change:

```
-    public $currentCategorySlug;
+    public string $currentCategorySlug = '';
```

PHP now throws an error if you assign null to this Class property because it now expects a string.

So basically, if you have the following page/component settings, it will throw an error:
```
url = /blog/:slug
layout = default

[blogCategories]
slug = "{{ :invalidSlug }}"
categoryPage = "blog"
==
```

Notice the `{{ :invalidSlug }}` assigned to the component's slug property when it should be `{{ :slug }}`

I suspect it's possible to trigger similar errors in other blog components as well because of the extra property validation that was added. This is not necessarily a bad thing, but might break badly written themes.

**Comment by 01Kuzma** [comment] 2023-05-07 17:04
@mjauvin , here it is:
```
title = "Portfolio"
url = "/portfolio/:page?"
layout = "default"
meta_description = "Desc..."
is_hidden = 0

[blogPosts]
pageNumber = "{{ :page }}"
categoryFilter = "{{ :slug }}"
postsPerPage = 10
noPostsMessage = "Įrašų nerasta"
sortOrder = "published_at desc"
categoryPage = "blog-category"
postPage = "blog-post"

[blogCategories]
slug = "{{ :slug }}"
displayEmpty = 0
categoryPage = "blog-category"
==
{% set posts = blogPosts.posts %}

```

**Comment by mjauvin** [comment] 2023-05-07 17:58
Just change:
```
[blogCategories]
slug = "{{ :slug }}"
```
To:
```
[blogCategories]
slug = "{{ :page }}"
```
To solve your issue.

**Comment by mjauvin** [comment] 2023-05-07 20:06
@LukeTowers should we change the component like this to restore original behavior ?
```diff
diff --git a/components/Categories.php b/components/Categories.php
index 10a958c..b0609e3 100644
--- a/components/Categories.php
+++ b/components/Categories.php
@@ -17,12 +17,12 @@ class Categories extends ComponentBase
     /**
      * Reference to the page name for linking to categories.
      */
-    public string $categoryPage = '';
+    public ?string $categoryPage = '';
 
     /**
      * Reference to the current category slug.
      */
-    public string $currentCategorySlug = '';
+    public ?string $currentCategorySlug = '';
 
     public function componentDetails(): array
     {
```

**Comment by 01Kuzma** [comment] 2023-05-08 08:46
@mjauvin it solves the `portfolio` issue.
Why did this happen? I've created this theme long time ago based on some tutorials, as I remember

And how to fix the main problem? What should I change here? `"\partials\intro.htm" at line 3.`
is pointing to `hero-slider/hero1.htm` with `Post List` component, which is:
```
[viewBag]

[blogPosts]
pageNumber = "{{ :page }}"
postsPerPage = 7
noPostsMessage = "No posts found"
sortOrder = "random"
categoryPage = "about"
postPage = "blog-post"
==
```

**Comment by mjauvin** [comment] 2023-05-08 11:54
> @mjauvin it solves the `portfolio` issue. Thank you! Why did this happen? I've created this theme long time ago based on some tutorials, as I remember

It happens because there are errors in your theme and the last update to the plugin introduced property validation for the components.

> And how to fix the main problem? What should I change here? `"\partials\intro.htm" at line 3.` is pointing to `hero-slider/hero1.htm` with `Post List` component, which is:

Please, always give the full settings section of the page you ask help for, otherwise it's hard to help.
 
> ```
> [viewBag]
> 
> [blogPosts]
> pageNumber = "{{ :page }}"
> postsPerPage = 7
> noPostsMessage = "No posts found"
> sortOrder = "random"
> categoryPage = "about"
> postPage = "blog-post"
> ==
> ```

**Comment by 01Kuzma** [comment] 2023-05-08 14:46
@mjauvin , sorry, have edited the last post

**Closed** 2023-05-08 19:23 UTC
Labels: Type: Bug

**Comment by 01Kuzma** [comment] 2023-05-10 18:41
@mjauvin , any thoughts regarding last [issue](https://github.com/wintercms/wn-blog-plugin/issues/38#issuecomment-1537984851)?
